{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Products",
    "description" : "",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "Erstellen Sie mit der Produkte-API eine Reihe von Produkten, die Ihre neuen Angebote repräsentieren, um eine bevorstehende Produkteinführung vorzubereiten. Vertriebsmitarbeiter können diese Produkte dann beim Erstellen von Zahlungslinks, Rechnungen und mehr verwenden.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Products Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/crm/objects/products"
    } ],
    "x-hubspot-introduction" : "Verwenden Sie die Produkte-API, um Ihre Produktbibliothek zu erstellen und zu verwalten. Dabei handelt es sich um die Sammlung von Waren und Dienstleistungen, die Ihr Unternehmen anbietet. Die Produkte in Ihrer Produktbibliothek können beim Erstellen von Deals, Zahlungslinks, Rechnungen und Angeboten als Artikel verwendet werden."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Batch"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Search"
  } ],
  "paths" : {
    "/crm/v3/objects/products/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch von Objekten nach interner ID oder eindeutigen Eigenschaftswerten lesen",
        "operationId" : "post-/crm/v3/objects/products/batch/read_read",
        "parameters" : [ {
          "name" : "archived",
          "in" : "query",
          "description" : "Ob nur Ergebnisse zurückgegeben werden sollen, die archiviert wurden.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BatchReadInputSimplePublicObjectId"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseSimplePublicObject"
                }
              }
            }
          },
          "207" : {
            "description" : "multiple statuses",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseSimplePublicObjectWithErrors"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      }
    },
    "/crm/v3/objects/products/{productId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Gelesen",
        "description" : "Ein durch „{productId}“ identifiziertes Objekt wird gelesen. „{productId}“ bezieht sich standardmäßig auf die interne Objekt-ID oder optional auf einen beliebigen Eigenschaftswert, wie im Abfrageparameter „idProperty“ spezifiziert. Es kann gesteuert werden, was über den Abfrageparameter „properties“ zurückgegeben wird.",
        "operationId" : "get-/crm/v3/objects/products/{productId}_getById",
        "parameters" : [ {
          "name" : "productId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "properties",
          "in" : "query",
          "description" : "Eine durch Kommas getrennte Liste der Eigenschaften, die in der Antwort zurückgegeben werden. Wenn Eigenschaften in dem oder den angeforderten Objekten nicht vorhanden sind, werden sie ignoriert.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "propertiesWithHistory",
          "in" : "query",
          "description" : "Eine durch Kommas getrennte Liste der Eigenschaften, die zusammen mit den jeweiligen Verlaufswerten zurückgegeben werden. Wenn Eigenschaften in dem oder den angeforderten Objekten nicht vorhanden sind, werden sie ignoriert.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "associations",
          "in" : "query",
          "description" : "Eine durch Kommas getrennte Liste der Objekttypen, für die zugeordnete IDs abgerufen werden sollen. Wenn angegebene Zuordnungen nicht existieren, werden sie ignoriert.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "archived",
          "in" : "query",
          "description" : "Ob nur Ergebnisse zurückgegeben werden sollen, die archiviert wurden.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "idProperty",
          "in" : "query",
          "description" : "Der Name einer Eigenschaft, deren Werte für diesen Objekttyp eindeutig sind",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SimplePublicObjectWithAssociations"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archivieren",
        "description" : "Zum Verschieben eines Objekts mit der ID „{productId}“ in den Papierkorb.",
        "operationId" : "delete-/crm/v3/objects/products/{productId}_archive",
        "parameters" : [ {
          "name" : "productId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Aktualisieren",
        "description" : "Ein durch „{productId}“ identifiziertes Objekt wird teilweise aktualisiert. „{productId}“ bezieht sich standardmäßig auf die interne Objekt-ID oder optional auf einen beliebigen Eigenschaftswert, wie im Abfrageparameter „idProperty“ spezifiziert. Bereitgestellte Eigenschaftswerte werden überschrieben. Schreibgeschützte und nicht vorhandene Eigenschaften werden ignoriert. Eigenschaftswerte können durch Übergabe einer leeren Zeichenfolge gelöscht werden.",
        "operationId" : "patch-/crm/v3/objects/products/{productId}_update",
        "parameters" : [ {
          "name" : "productId",
          "in" : "path",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "idProperty",
          "in" : "query",
          "description" : "Der Name einer Eigenschaft, deren Werte für diesen Objekttyp eindeutig sind",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/SimplePublicObjectInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SimplePublicObject"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      }
    },
    "/crm/v3/objects/products/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Einen Batch mit Objekten nach ID archivieren",
        "operationId" : "post-/crm/v3/objects/products/batch/archive_archive",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BatchInputSimplePublicObjectId"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      }
    },
    "/crm/v3/objects/products/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Einen Batch mit Objekten erstellen",
        "operationId" : "post-/crm/v3/objects/products/batch/create_create",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BatchInputSimplePublicObjectInputForCreate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseSimplePublicObject"
                }
              }
            }
          },
          "207" : {
            "description" : "multiple statuses",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseSimplePublicObjectWithErrors"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      }
    },
    "/crm/v3/objects/products/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch von Objekten nach interner ID oder eindeutigen Eigenschaftswerten aktualisieren",
        "operationId" : "post-/crm/v3/objects/products/batch/update_update",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/BatchInputSimplePublicObjectBatchInput"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseSimplePublicObject"
                }
              }
            }
          },
          "207" : {
            "description" : "multiple statuses",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BatchResponseSimplePublicObjectWithErrors"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      }
    },
    "/crm/v3/objects/products" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Liste",
        "description" : "Zum Lesen einer Seite von Objekten. Steuern Sie, was über den „properties“-Abfrageparameter zurückgegeben wird.",
        "operationId" : "get-/crm/v3/objects/products_getPage",
        "parameters" : [ {
          "name" : "limit",
          "in" : "query",
          "description" : "Die maximale Anzahl der Ergebnisse, die pro Seite angezeigt werden",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32",
            "default" : 10
          }
        }, {
          "name" : "after",
          "in" : "query",
          "description" : "Das Paging-Cursor-Token der zuletzt erfolgreich gelesenen Ressource wird als „paging.next.after“-JSON-Eigenschaft einer ausgelesenen Antwort mit weiteren Ergebnissen zurückgegeben.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "properties",
          "in" : "query",
          "description" : "Eine durch Kommas getrennte Liste der Eigenschaften, die in der Antwort zurückgegeben werden. Wenn Eigenschaften in dem oder den angeforderten Objekten nicht vorhanden sind, werden sie ignoriert.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "propertiesWithHistory",
          "in" : "query",
          "description" : "Eine durch Kommas getrennte Liste der Eigenschaften, die zusammen mit den jeweiligen Verlaufswerten zurückgegeben werden. Wenn Eigenschaften in dem oder den angeforderten Objekten nicht vorhanden sind, werden sie ignoriert. Mit diesem Parameter wird die maximale Anzahl der Objekte reduziert, die bei einer einzigen Anfrage gelesen werden können.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "associations",
          "in" : "query",
          "description" : "Eine durch Kommas getrennte Liste der Objekttypen, für die zugeordnete IDs abgerufen werden sollen. Wenn angegebene Zuordnungen nicht existieren, werden sie ignoriert.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "archived",
          "in" : "query",
          "description" : "Ob nur Ergebnisse zurückgegeben werden sollen, die archiviert wurden.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponseSimplePublicObjectWithAssociationsForwardPaging"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Erstellen",
        "description" : "Erstellt ein CRM-Objekt mit den angegebenen Eigenschaften und gibt eine Kopie des Objekts einschließlich der ID zurück. Dokumentation und Beispiele zum Erstellen von Standardobjekten werden bereitgestellt.",
        "operationId" : "post-/crm/v3/objects/products_create",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/SimplePublicObjectInputForCreate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/SimplePublicObject"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ]
      }
    },
    "/crm/v3/objects/products/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/products/search_doSearch",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PublicObjectSearchRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponseWithTotalSimplePublicObjectForwardPaging"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "StandardError" : {
        "required" : [ "category", "context", "errors", "links", "message", "status" ],
        "type" : "object",
        "properties" : {
          "subCategory" : {
            "type" : "object",
            "properties" : { }
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            }
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "id" : {
            "type" : "string"
          },
          "category" : {
            "type" : "string"
          },
          "message" : {
            "type" : "string"
          },
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          },
          "status" : {
            "type" : "string"
          }
        }
      },
      "CollectionResponseAssociatedId" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "paging" : {
            "$ref" : "#/components/schemas/Paging"
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/AssociatedId"
            }
          }
        }
      },
      "PublicAssociationsForObject" : {
        "required" : [ "to", "types" ],
        "type" : "object",
        "properties" : {
          "types" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/AssociationSpec"
            }
          },
          "to" : {
            "$ref" : "#/components/schemas/PublicObjectId"
          }
        }
      },
      "BatchResponseSimplePublicObject" : {
        "required" : [ "completedAt", "results", "startedAt", "status" ],
        "type" : "object",
        "properties" : {
          "completedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "requestedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "startedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObject"
            }
          },
          "status" : {
            "type" : "string",
            "enum" : [ "PENDING", "PROCESSING", "CANCELED", "COMPLETE" ]
          }
        }
      },
      "FilterGroup" : {
        "required" : [ "filters" ],
        "type" : "object",
        "properties" : {
          "filters" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Filter"
            }
          }
        }
      },
      "ErrorDetail" : {
        "required" : [ "message" ],
        "type" : "object",
        "properties" : {
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          },
          "code" : {
            "type" : "string",
            "description" : "The status code associated with the error detail"
          },
          "in" : {
            "type" : "string",
            "description" : "The name of the field or parameter in which the error was found."
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : {
              "missingScopes" : [ "scope1", "scope2" ]
            }
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate"
          }
        }
      },
      "ForwardPaging" : {
        "type" : "object",
        "properties" : {
          "next" : {
            "$ref" : "#/components/schemas/NextPage"
          }
        }
      },
      "SimplePublicObjectId" : {
        "required" : [ "id" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          }
        }
      },
      "BatchReadInputSimplePublicObjectId" : {
        "required" : [ "inputs", "properties", "propertiesWithHistory" ],
        "type" : "object",
        "properties" : {
          "propertiesWithHistory" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "idProperty" : {
            "type" : "string"
          },
          "inputs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObjectId"
            }
          },
          "properties" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      },
      "BatchInputSimplePublicObjectId" : {
        "required" : [ "inputs" ],
        "type" : "object",
        "properties" : {
          "inputs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObjectId"
            }
          }
        }
      },
      "ValueWithTimestamp" : {
        "required" : [ "sourceType", "timestamp", "value" ],
        "type" : "object",
        "properties" : {
          "sourceId" : {
            "type" : "string"
          },
          "sourceType" : {
            "type" : "string"
          },
          "sourceLabel" : {
            "type" : "string"
          },
          "updatedByUserId" : {
            "type" : "integer",
            "format" : "int32"
          },
          "value" : {
            "type" : "string"
          },
          "timestamp" : {
            "type" : "string",
            "format" : "date-time"
          }
        }
      },
      "CollectionResponseWithTotalSimplePublicObjectForwardPaging" : {
        "required" : [ "results", "total" ],
        "type" : "object",
        "properties" : {
          "total" : {
            "type" : "integer",
            "format" : "int32"
          },
          "paging" : {
            "$ref" : "#/components/schemas/ForwardPaging"
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObject"
            }
          }
        }
      },
      "SimplePublicObject" : {
        "required" : [ "createdAt", "id", "properties", "updatedAt" ],
        "type" : "object",
        "properties" : {
          "createdAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "archived" : {
            "type" : "boolean",
            "example" : false
          },
          "archivedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "propertiesWithHistory" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/components/schemas/ValueWithTimestamp"
              }
            }
          },
          "id" : {
            "type" : "string",
            "example" : "512"
          },
          "properties" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string",
              "nullable" : true
            },
            "example" : {
              "property_date" : "1572480000000",
              "property_radio" : "option_1",
              "property_number" : "17",
              "property_string" : "value",
              "property_checkbox" : "false",
              "property_dropdown" : "choice_b",
              "property_multiple_checkboxes" : "chocolate;strawberry"
            }
          },
          "updatedAt" : {
            "type" : "string",
            "format" : "date-time"
          }
        },
        "example" : {
          "id" : "512",
          "properties" : {
            "createdate" : "2019-10-30T03:30:17.883Z",
            "description" : "Onboarding service for data product",
            "hs_cost_of_goods_sold" : "600.00",
            "hs_lastmodifieddate" : "2019-12-07T16:50:06.678Z",
            "hs_recurring_billing_period" : "12",
            "hs_sku" : "191902",
            "name" : "Implementation Service ",
            "price" : "6000.00"
          },
          "createdAt" : "2019-10-30T03:30:17.883Z",
          "updatedAt" : "2019-12-07T16:50:06.678Z",
          "archived" : false
        }
      },
      "PublicObjectId" : {
        "required" : [ "id" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          }
        }
      },
      "Paging" : {
        "type" : "object",
        "properties" : {
          "next" : {
            "$ref" : "#/components/schemas/NextPage"
          },
          "prev" : {
            "$ref" : "#/components/schemas/PreviousPage"
          }
        }
      },
      "PublicObjectSearchRequest" : {
        "required" : [ "after", "filterGroups", "limit", "properties", "sorts" ],
        "type" : "object",
        "properties" : {
          "query" : {
            "type" : "string"
          },
          "limit" : {
            "type" : "integer",
            "format" : "int32"
          },
          "after" : {
            "type" : "string"
          },
          "sorts" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "properties" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "filterGroups" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/FilterGroup"
            }
          }
        }
      },
      "Error" : {
        "required" : [ "category", "correlationId", "message" ],
        "type" : "object",
        "properties" : {
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : {
              "missingScopes" : [ "scope1", "scope2" ],
              "invalidPropertyName" : [ "propertyValue" ]
            }
          },
          "correlationId" : {
            "type" : "string",
            "description" : "A unique identifier for the request. Include this value with any error reports or support tickets",
            "format" : "uuid",
            "example" : "aeb5f871-7f07-4993-9211-075dc63e7cbf"
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A map of link names to associated URIs containing documentation about the error or recommended remediation steps",
            "example" : {
              "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
            }
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate",
            "example" : "Invalid input (details will vary based on the error)"
          },
          "category" : {
            "type" : "string",
            "description" : "The error category",
            "example" : "VALIDATION_ERROR"
          },
          "errors" : {
            "type" : "array",
            "description" : "further information about the error",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          }
        },
        "example" : {
          "message" : "Invalid input (details will vary based on the error)",
          "correlationId" : "aeb5f871-7f07-4993-9211-075dc63e7cbf",
          "category" : "VALIDATION_ERROR",
          "links" : {
            "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
          }
        }
      },
      "BatchResponseSimplePublicObjectWithErrors" : {
        "required" : [ "completedAt", "results", "startedAt", "status" ],
        "type" : "object",
        "properties" : {
          "completedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "numErrors" : {
            "type" : "integer",
            "format" : "int32"
          },
          "requestedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "startedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObject"
            }
          },
          "errors" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/StandardError"
            }
          },
          "status" : {
            "type" : "string",
            "enum" : [ "PENDING", "PROCESSING", "CANCELED", "COMPLETE" ]
          }
        }
      },
      "SimplePublicObjectInput" : {
        "required" : [ "properties" ],
        "type" : "object",
        "properties" : {
          "properties" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "example" : {
              "property_date" : "1572480000000",
              "property_radio" : "option_1",
              "property_number" : "17",
              "property_string" : "value",
              "property_checkbox" : "false",
              "property_dropdown" : "choice_b",
              "property_multiple_checkboxes" : "chocolate;strawberry"
            }
          }
        },
        "example" : {
          "properties" : {
            "name" : "Implementation Service ",
            "price" : "6000.00",
            "hs_sku" : "191902",
            "description" : "Onboarding service for data product",
            "hs_cost_of_goods_sold" : "600.00",
            "hs_recurring_billing_period" : "12"
          },
          "associations" : [ {
            "to" : {
              "id" : "101"
            },
            "types" : [ {
              "associationCategory" : "HUBSPOT_DEFINED",
              "associationTypeId" : 2
            } ]
          } ]
        }
      },
      "CollectionResponseSimplePublicObjectWithAssociationsForwardPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "paging" : {
            "$ref" : "#/components/schemas/ForwardPaging"
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObjectWithAssociations"
            }
          }
        }
      },
      "AssociationSpec" : {
        "required" : [ "associationCategory", "associationTypeId" ],
        "type" : "object",
        "properties" : {
          "associationCategory" : {
            "type" : "string",
            "enum" : [ "HUBSPOT_DEFINED", "USER_DEFINED", "INTEGRATOR_DEFINED" ]
          },
          "associationTypeId" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "SimplePublicObjectWithAssociations" : {
        "required" : [ "createdAt", "id", "properties", "updatedAt" ],
        "type" : "object",
        "properties" : {
          "associations" : {
            "type" : "object",
            "additionalProperties" : {
              "$ref" : "#/components/schemas/CollectionResponseAssociatedId"
            }
          },
          "createdAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "archived" : {
            "type" : "boolean"
          },
          "archivedAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "propertiesWithHistory" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/components/schemas/ValueWithTimestamp"
              }
            }
          },
          "id" : {
            "type" : "string"
          },
          "properties" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string",
              "nullable" : true
            }
          },
          "updatedAt" : {
            "type" : "string",
            "format" : "date-time"
          }
        },
        "example" : {
          "properties" : {
            "createdate" : "2019-10-30T03:30:17.883Z",
            "description" : "Onboarding service for data product",
            "hs_cost_of_goods_sold" : "600.00",
            "hs_lastmodifieddate" : "2019-12-07T16:50:06.678Z",
            "hs_recurring_billing_period" : "12",
            "hs_sku" : "191902",
            "name" : "Implementation Service ",
            "price" : "6000.00"
          }
        }
      },
      "Filter" : {
        "required" : [ "operator", "propertyName" ],
        "type" : "object",
        "properties" : {
          "highValue" : {
            "type" : "string"
          },
          "propertyName" : {
            "type" : "string"
          },
          "values" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "value" : {
            "type" : "string"
          },
          "operator" : {
            "type" : "string",
            "description" : "null",
            "enum" : [ "EQ", "NEQ", "LT", "LTE", "GT", "GTE", "BETWEEN", "IN", "NOT_IN", "HAS_PROPERTY", "NOT_HAS_PROPERTY", "CONTAINS_TOKEN", "NOT_CONTAINS_TOKEN" ]
          }
        }
      },
      "BatchInputSimplePublicObjectBatchInput" : {
        "required" : [ "inputs" ],
        "type" : "object",
        "properties" : {
          "inputs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObjectBatchInput"
            }
          }
        }
      },
      "BatchInputSimplePublicObjectInputForCreate" : {
        "required" : [ "inputs" ],
        "type" : "object",
        "properties" : {
          "inputs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/SimplePublicObjectInputForCreate"
            }
          }
        }
      },
      "PreviousPage" : {
        "required" : [ "before" ],
        "type" : "object",
        "properties" : {
          "before" : {
            "type" : "string"
          },
          "link" : {
            "type" : "string"
          }
        }
      },
      "SimplePublicObjectBatchInput" : {
        "required" : [ "id", "properties" ],
        "type" : "object",
        "properties" : {
          "idProperty" : {
            "type" : "string",
            "example" : "my_unique_property_name"
          },
          "id" : {
            "type" : "string"
          },
          "properties" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          }
        },
        "example" : {
          "id" : "1",
          "properties" : {
            "name" : "Implementation Service ",
            "price" : "6000.00",
            "hs_sku" : "191902",
            "description" : "Onboarding service for data product",
            "hs_cost_of_goods_sold" : "600.00",
            "hs_recurring_billing_period" : "12"
          }
        }
      },
      "AssociatedId" : {
        "required" : [ "id", "type" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "type" : {
            "type" : "string"
          }
        }
      },
      "NextPage" : {
        "required" : [ "after" ],
        "type" : "object",
        "properties" : {
          "link" : {
            "type" : "string",
            "example" : "?after=NTI1Cg%3D%3D"
          },
          "after" : {
            "type" : "string",
            "example" : "NTI1Cg%3D%3D"
          }
        },
        "example" : {
          "after" : "NTI1Cg%3D%3D",
          "link" : "?after=NTI1Cg%3D%3D"
        }
      },
      "SimplePublicObjectInputForCreate" : {
        "required" : [ "associations", "properties" ],
        "type" : "object",
        "properties" : {
          "associations" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PublicAssociationsForObject"
            }
          },
          "properties" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          }
        },
        "example" : {
          "properties" : {
            "name" : "Implementation Service ",
            "price" : "6000.00",
            "hs_sku" : "191902",
            "description" : "Onboarding service for data product",
            "hs_cost_of_goods_sold" : "600.00",
            "hs_recurring_billing_period" : "12"
          },
          "associations" : [ {
            "to" : {
              "id" : "101"
            },
            "types" : [ {
              "associationCategory" : "HUBSPOT_DEFINED",
              "associationTypeId" : 2
            } ]
          } ]
        }
      }
    },
    "responses" : {
      "Error" : {
        "description" : "An error occurred.",
        "content" : {
          "*/*" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "media_bridge.read" : "Read media and media events",
              "crm.objects.goals.read" : "Read goals",
              "tickets" : "Read and write tickets",
              "crm.objects.custom.read" : "View custom object records",
              "e-commerce" : "e-commerce",
              "crm.objects.custom.write" : "Change custom object records"
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.contacts.write" : " ",
              "crm.objects.quotes.write" : "Quotes",
              "crm.objects.companies.read" : " ",
              "crm.objects.carts.write" : "Write cart",
              "crm.objects.deals.write" : " ",
              "crm.objects.users.write" : "Write User CRM objects",
              "crm.objects.orders.read" : "Read Orders",
              "crm.objects.leads.read" : "Read lead objects",
              "crm.objects.orders.write" : "Write orders",
              "crm.objects.subscriptions.read" : "Read Commerce Subscriptions",
              "crm.objects.line_items.write" : "Line Items",
              "crm.objects.companies.write" : " ",
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.line_items.read" : "Line Items",
              "crm.objects.leads.write" : "Modify lead objects",
              "crm.objects.contacts.read" : " ",
              "crm.objects.invoices.read" : "Read invoices objects",
              "crm.objects.quotes.read" : "Quotes",
              "crm.objects.partner-clients.write" : "Modify Partner Client CRM objects",
              "crm.objects.partner-clients.read" : "View Partner Client CRM objects",
              "crm.objects.deals.read" : " ",
              "crm.objects.carts.read" : "Read carts",
              "crm.objects.commercepayments.read" : "Read the COMMERCE_PAYMENT object."
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  },
  "x-hubspot-documentation-banner" : "NONE"
}