{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "ユーザープロビジョニング",
    "description" : "Add, manage, and remove users from your account",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-documentation-banner" : "NONE",
    "x-hubspot-api-use-case" : "HubSpot外のシステムで従業員のアクセスデータを管理しており、特定のユーザーが確実にHubSpotアカウントの適切なチームに動的に割り当てられるようにしたいと考えています。",
    "x-hubspot-related-documentation" : [ {
      "name" : "User Provisioning Guide",
      "url" : "https://developers.hubspot.com/beta-docs/guides/api/settings/users/user-provisioning"
    } ],
    "x-hubspot-introduction" : "ユーザープロビジョニングAPIを使用して、関連付けられているチームや役割を含めて、HubSpotアカウントのユーザーの作成や管理を行います。"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "チーム"
  }, {
    "name" : "役割"
  }, {
    "name" : "ユーザー"
  } ],
  "paths" : {
    "/settings/v3/users/teams" : {
      "get" : {
        "tags" : [ "チーム" ],
        "summary" : "このアカウントのチームに関する詳細を確認",
        "description" : "このアカウントのチームを表示",
        "operationId" : "get-/settings/v3/users/teams_getAll",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePublicTeamNoPaging"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2_legacy" : [ "settings.users.teams.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.teams.read" ]
        } ]
      }
    },
    "/settings/v3/users/roles" : {
      "get" : {
        "tags" : [ "役割" ],
        "summary" : "アカウントでの役割が取得されます",
        "description" : "アカウントでの役割が取得されます",
        "operationId" : "get-/settings/v3/users/roles_getAll",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePublicPermissionSetNoPaging"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      }
    },
    "/settings/v3/users/" : {
      "get" : {
        "tags" : [ "ユーザー" ],
        "summary" : "アカウントからユーザーのリストが取得されます",
        "description" : "アカウントからユーザーのリストが取得されます",
        "operationId" : "get-/settings/v3/users/_getPage",
        "parameters" : [ {
          "name" : "limit",
          "in" : "query",
          "description" : "取得するユーザーの人数",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "after",
          "in" : "query",
          "description" : "結果では、ページあたり最大100人のユーザーが表示されます。追加の結果がある場合は次のページに表示されます。",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePublicUserForwardPaging"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーを追加",
        "description" : "新規ユーザーにはコンタクトに基づいて最小限の権限が付与されます。ウェルカムEメールを送信すれば、パスワードを設定してHubSpotにログインするよう促すことができます。",
        "operationId" : "post-/settings/v3/users/_create",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UserProvisionRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PublicUser"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    },
    "/settings/v3/users/{userId}" : {
      "get" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーが取得されます",
        "description" : "「userId」によって特定されるユーザーが取得されます。「userId」は既定ではユーザーのIDを指しますが、必要に応じて「IdProperty」クエリーパラメーターによって指定されたEメールを指すこともできます。",
        "operationId" : "get-/settings/v3/users/{userId}_getById",
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "description" : "取得するユーザーのID",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "idProperty",
          "in" : "query",
          "description" : "固有のユーザー値を含むプロパティーの名前。有効な値は「USER_ID」（既定）または「EMAIL」です",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "USER_ID", "EMAIL" ]
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PublicUser"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "private_apps" : [ "crm.objects.users.read" ]
        }, {
          "oauth2" : [ "crm.objects.users.read" ]
        }, {
          "private_apps_legacy" : [ "settings.users.read" ]
        }, {
          "oauth2_legacy" : [ "settings.users.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーが変更されます",
        "description" : "「userId」によって特定されるユーザーが変更されます。「userId」は既定ではユーザーのIDを指しますが、必要に応じて「IdProperty」クエリーパラメーターによって指定されたEメールを指すこともできます。",
        "operationId" : "put-/settings/v3/users/{userId}_replace",
        "parameters" : [ {
          "name" : "idProperty",
          "in" : "query",
          "description" : "固有のユーザー値を含むプロパティーの名前。有効な値は「USER_ID」（既定）または「EMAIL」です",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "USER_ID", "EMAIL" ]
          }
        }, {
          "name" : "userId",
          "in" : "path",
          "description" : "取得するユーザーのID",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/PublicUserUpdate"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PublicUser"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "ユーザー" ],
        "summary" : "ユーザーが削除されます",
        "description" : "「userId」によって特定されるユーザーが削除されます。「userId」は既定ではユーザーのIDを指しますが、必要に応じて「IdProperty」クエリーパラメーターによって指定されたEメールを指すこともできます。",
        "operationId" : "delete-/settings/v3/users/{userId}_archive",
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "description" : "削除するユーザーのID",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "idProperty",
          "in" : "query",
          "description" : "固有のユーザー値を含むプロパティーの名前。有効な値は「USER_ID」（既定）または「EMAIL」です",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "USER_ID", "EMAIL" ]
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "No content",
            "content" : { }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "private_apps_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2_legacy" : [ "settings.users.write" ]
        }, {
          "oauth2" : [ "crm.objects.users.write" ]
        }, {
          "private_apps" : [ "crm.objects.users.write" ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "ErrorDetail" : {
        "required" : [ "message" ],
        "type" : "object",
        "properties" : {
          "subCategory" : {
            "type" : "string",
            "description" : "エラーに関するより具体的な詳細が含まれる特定のカテゴリー"
          },
          "code" : {
            "type" : "string",
            "description" : "エラーの詳細に関連付けられているステータスコード"
          },
          "in" : {
            "type" : "string",
            "description" : "エラーが見つかったフィールドまたはパラメーターの名前。"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "エラー条件に関する状況",
            "example" : {
              "missingScopes" : [ "scope1", "scope2" ]
            }
          },
          "message" : {
            "type" : "string",
            "description" : "エラーと修正手順（該当する場合）を記した人間が読めるメッセージ"
          }
        }
      },
      "ForwardPaging" : {
        "type" : "object",
        "properties" : {
          "next" : {
            "$ref" : "#/components/schemas/NextPage"
          }
        }
      },
      "PublicUser" : {
        "required" : [ "email", "id" ],
        "type" : "object",
        "properties" : {
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "primaryTeamId" : {
            "type" : "string",
            "description" : "ユーザーのプライマリーチーム",
            "example" : "101"
          },
          "roleIds" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "sendWelcomeEmail" : {
            "type" : "boolean"
          },
          "roleId" : {
            "type" : "string",
            "description" : "ユーザーの役割",
            "example" : "100"
          },
          "secondaryTeamIds" : {
            "type" : "array",
            "description" : "ユーザーの追加チーム",
            "example" : [ "102" ],
            "items" : {
              "type" : "string"
            }
          },
          "id" : {
            "type" : "string",
            "description" : "ユーザーの固有ID",
            "example" : "123"
          },
          "superAdmin" : {
            "type" : "boolean",
            "example" : false
          },
          "email" : {
            "type" : "string",
            "description" : "ユーザーのEメール",
            "example" : "newUser@email.com"
          }
        },
        "description" : "A user",
        "example" : {
          "id" : "123",
          "email" : "newUser@email.com",
          "roleId" : "100",
          "primaryTeamId" : "101",
          "secondaryTeamIds" : [ "102" ],
          "superAdmin" : "false"
        }
      },
      "CollectionResponsePublicPermissionSetNoPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PublicPermissionSet"
            }
          }
        }
      },
      "PublicTeam" : {
        "required" : [ "id", "name", "secondaryUserIds", "userIds" ],
        "type" : "object",
        "properties" : {
          "userIds" : {
            "type" : "array",
            "description" : "このチームのプライマリーメンバー",
            "example" : [ "123" ],
            "items" : {
              "type" : "string"
            }
          },
          "name" : {
            "type" : "string",
            "description" : "チームの名前",
            "example" : "Test Team"
          },
          "id" : {
            "type" : "string",
            "description" : "チームの固有ID",
            "example" : "100"
          },
          "secondaryUserIds" : {
            "type" : "array",
            "description" : "このチームのセカンダリーメンバーまたは追加メンバー",
            "example" : [ "124" ],
            "items" : {
              "type" : "string"
            }
          }
        },
        "description" : "A team that can be assigned to a user",
        "example" : {
          "id" : "100",
          "name" : "Test Team",
          "userIds" : [ "123" ],
          "secondaryUserIds" : [ "124" ]
        }
      },
      "CollectionResponsePublicTeamNoPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PublicTeam"
            }
          }
        }
      },
      "CollectionResponsePublicUserForwardPaging" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "paging" : {
            "$ref" : "#/components/schemas/ForwardPaging"
          },
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PublicUser"
            }
          }
        }
      },
      "UserProvisionRequest" : {
        "required" : [ "email" ],
        "type" : "object",
        "properties" : {
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "primaryTeamId" : {
            "type" : "string",
            "description" : "ユーザーのプライマリーチーム",
            "example" : "101"
          },
          "sendWelcomeEmail" : {
            "type" : "boolean",
            "description" : "ウェルカムEメールを送信するかどうか",
            "example" : true
          },
          "roleId" : {
            "type" : "string",
            "description" : "ユーザーの役割",
            "example" : "100"
          },
          "secondaryTeamIds" : {
            "type" : "array",
            "description" : "ユーザーの追加チーム",
            "example" : [ "102" ],
            "items" : {
              "type" : "string"
            }
          },
          "email" : {
            "type" : "string",
            "description" : "作成されたユーザーのEメール",
            "example" : "newUser@email.com"
          }
        },
        "description" : "A user creation request",
        "example" : {
          "email" : "newUser@email.com",
          "roleId" : "100",
          "primaryTeamId" : "101",
          "secondaryTeamIds" : [ "102" ],
          "sendWelcomeEmail" : "true"
        }
      },
      "PublicUserUpdate" : {
        "type" : "object",
        "properties" : {
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "primaryTeamId" : {
            "type" : "string",
            "description" : "ユーザーのプライマリーチーム",
            "example" : "101"
          },
          "roleId" : {
            "type" : "string",
            "description" : "ユーザーの役割",
            "example" : "100"
          },
          "secondaryTeamIds" : {
            "type" : "array",
            "description" : "ユーザーの追加チーム",
            "example" : [ "102" ],
            "items" : {
              "type" : "string"
            }
          }
        },
        "description" : "A user to update",
        "example" : {
          "roleId" : "100",
          "primaryTeamId" : "101",
          "secondaryTeamIds" : [ "102" ]
        }
      },
      "Error" : {
        "required" : [ "category", "correlationId", "message" ],
        "type" : "object",
        "properties" : {
          "subCategory" : {
            "type" : "string",
            "description" : "エラーに関するより具体的な詳細が含まれる特定のカテゴリー"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "エラー条件に関する状況",
            "example" : {
              "missingScopes" : [ "scope1", "scope2" ],
              "invalidPropertyName" : [ "propertyValue" ]
            }
          },
          "correlationId" : {
            "type" : "string",
            "description" : "リクエストの固有ID。エラーレポートまたはサポートチケットには必ずこの値を含めてください",
            "format" : "uuid",
            "example" : "aeb5f871-7f07-4993-9211-075dc63e7cbf"
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "エラーまたは推奨の修正手順に関するドキュメントが含まれる関連付けられたURIへのリンク名のひも付け",
            "example" : {
              "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
            }
          },
          "message" : {
            "type" : "string",
            "description" : "エラーと修正手順（該当する場合）を記した人間が読めるメッセージ",
            "example" : "Invalid input (details will vary based on the error)"
          },
          "category" : {
            "type" : "string",
            "description" : "エラーカテゴリー",
            "example" : "VALIDATION_ERROR"
          },
          "errors" : {
            "type" : "array",
            "description" : "エラーに関する詳細情報",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          }
        },
        "example" : {
          "message" : "Invalid input (details will vary based on the error)",
          "correlationId" : "aeb5f871-7f07-4993-9211-075dc63e7cbf",
          "category" : "VALIDATION_ERROR",
          "links" : {
            "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
          }
        }
      },
      "NextPage" : {
        "required" : [ "after" ],
        "type" : "object",
        "properties" : {
          "link" : {
            "type" : "string"
          },
          "after" : {
            "type" : "string"
          }
        }
      },
      "PublicPermissionSet" : {
        "required" : [ "id", "name", "requiresBillingWrite" ],
        "type" : "object",
        "properties" : {
          "requiresBillingWrite" : {
            "type" : "boolean",
            "description" : "この役割が有料シートを持っていてユーザーへの割り当て／割り当て解除に請求の書き込みスコープが必要かどうか",
            "example" : false
          },
          "name" : {
            "type" : "string",
            "description" : "役割の名前",
            "example" : "Test Role"
          },
          "id" : {
            "type" : "string",
            "description" : "役割の固有ID",
            "example" : "100"
          }
        },
        "description" : "A role that can be assigned to a user",
        "example" : {
          "id" : "100",
          "name" : "Test Role",
          "requiresBillingWrite" : "False"
        }
      }
    },
    "responses" : {
      "Error" : {
        "description" : "An error occurred.",
        "content" : {
          "*/*" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "settings.users.read" : "View account data.",
              "settings.users.write" : "Create, modify, and delete users on your account",
              "settings.users.teams.read" : "View teams for this account."
            }
          }
        }
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.users.read" : "Read User CRM objects",
              "crm.objects.users.write" : "Write User CRM objects"
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Ruby", "Python" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  },
  "x-hubspot-documentation-banner" : "NONE"
}