{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Account Account Info",
    "description" : "Get information about a HubSpot account and its API usage.",
    "version" : "2025-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE"
    },
    "x-hubspot-api-use-case" : "Your security team wants deeper insight into which internal users are accessing your HubSpot account data and you need to provide the associated activity data.",
    "x-hubspot-related-documentation" : [ {
      "name" : "Account information API guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/settings/account-information-api"
    } ],
    "x-hubspot-introduction" : "Use the account information API to retrieve login and security history for your account, as well as usage data for a public app."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Activity"
  }, {
    "name" : "Details__SE_PT_EM_BE_R_2025"
  }, {
    "name" : "Usage"
  }, {
    "name" : "Usage__SE_PT_EM_BE_R_2025"
  }, {
    "name" : "Details"
  }, {
    "name" : "Activity__SE_PT_EM_BE_R_2025"
  } ],
  "paths" : {
    "/account-info/2025-09/activity/audit-logs" : {
      "get" : {
        "tags" : [ "Activity__SE_PT_EM_BE_R_2025" ],
        "summary" : "Get a list of audit logs for a HubSpot account.",
        "description" : "Get audit logs.",
        "operationId" : "get-/account-info/2025-09/activity/audit-logs",
        "parameters" : [ {
          "name" : "after",
          "in" : "query",
          "description" : "The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "The maximum number of results to display per page.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "actingUserId",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "integer",
              "format" : "int32"
            }
          }
        }, {
          "name" : "occurredAfter",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time"
          }
        }, {
          "name" : "occurredBefore",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time"
          }
        }, {
          "name" : "sort",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePublicApiUserActionEvent"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "account-info.security.read" ]
        }, {
          "private_apps" : [ "account-info.security.read" ]
        } ]
      }
    },
    "/account-info/2025-09/details" : {
      "get" : {
        "tags" : [ "Details__SE_PT_EM_BE_R_2025" ],
        "summary" : "Retrieve account details",
        "description" : "Retrieve account details such as the account type, time zone, currencies, and data hosting location. ",
        "operationId" : "get-/account-info/2025-09/details",
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/PortalInformationResponse"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "ACCEPTANCE_TEST.both.40420451.367530" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.both.40420451.367530" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "ACCEPTANCE_TEST.scopes.delete.40420451.368267" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.scopes.delete.40420451.368267" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.scopes.40420451.367375" ]
        }, {
          "oauth2" : [ "ACCEPTANCE_TEST.scopes.40420451.367375" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "oauth2" : [ "ACCEPTANCE_TEST.create.40420451.367186" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.create.40420451.367186" ]
        } ]
      }
    },
    "/account-info/2025-09/api-usage/daily/private-apps" : {
      "get" : {
        "tags" : [ "Usage__SE_PT_EM_BE_R_2025" ],
        "summary" : "Retrieve private app daily API usage",
        "description" : "Retrieve the daily API usage for private apps in the account, along with information about usage limits.",
        "operationId" : "get-/account-info/2025-09/api-usage/daily/private-apps",
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponseApiUsage"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "ACCEPTANCE_TEST.both.40420451.367530" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.both.40420451.367530" ]
        }, {
          "oauth2" : [ "oauth" ]
        }, {
          "oauth2" : [ "ACCEPTANCE_TEST.scopes.delete.40420451.368267" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.scopes.delete.40420451.368267" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.scopes.40420451.367375" ]
        }, {
          "oauth2" : [ "ACCEPTANCE_TEST.scopes.40420451.367375" ]
        }, {
          "private_apps" : [ "oauth" ]
        }, {
          "oauth2" : [ "ACCEPTANCE_TEST.create.40420451.367186" ]
        }, {
          "private_apps" : [ "ACCEPTANCE_TEST.create.40420451.367186" ]
        } ]
      }
    },
    "/account-info/2025-09/activity/security" : {
      "get" : {
        "tags" : [ "Activity__SE_PT_EM_BE_R_2025" ],
        "summary" : "Get security activity for a HubSpot account",
        "description" : "Get security activity",
        "operationId" : "get-/account-info/2025-09/activity/security",
        "parameters" : [ {
          "name" : "after",
          "in" : "query",
          "description" : "The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "The maximum number of results to display per page.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "userId",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "fromTimestamp",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        }, {
          "name" : "toTimestamp",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int64"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponseHydratedCriticalAction"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "account-info.security.read" ]
        }, {
          "private_apps" : [ "account-info.security.read" ]
        } ]
      }
    },
    "/account-info/2025-09/activity/login" : {
      "get" : {
        "tags" : [ "Activity__SE_PT_EM_BE_R_2025" ],
        "summary" : "Get login activity for a HubSpot account.",
        "description" : "Get login activity.",
        "operationId" : "get-/account-info/2025-09/activity/login",
        "parameters" : [ {
          "name" : "after",
          "in" : "query",
          "description" : "The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "The maximum number of results to display per page.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "userId",
          "in" : "query",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponsePublicLoginAudit"
                }
              }
            }
          },
          "default" : {
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "account-info.security.read" ]
        }, {
          "private_apps" : [ "account-info.security.read" ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "CollectionResponsePublicLoginAudit" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PublicLoginAudit"
            }
          },
          "paging" : {
            "$ref" : "#/components/schemas/Paging"
          }
        }
      },
      "CollectionResponseApiUsage" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ApiUsage"
            }
          },
          "paging" : {
            "$ref" : "#/components/schemas/Paging"
          }
        }
      },
      "PublicLoginAudit" : {
        "required" : [ "id", "loginAt", "loginSucceeded" ],
        "type" : "object",
        "properties" : {
          "regionCode" : {
            "type" : "string",
            "description" : "The approximate region code of the login",
            "example" : "d"
          },
          "countryCode" : {
            "type" : "string",
            "description" : "The approximate country code of the login",
            "example" : "ie"
          },
          "ipAddress" : {
            "type" : "string",
            "description" : "IP address where the activity originated.",
            "example" : "45.56.67.89"
          },
          "location" : {
            "type" : "string"
          },
          "userAgent" : {
            "type" : "string",
            "description" : "Information about the device used for logging in.",
            "example" : "Mozilla/5.0 (Linux; Android 11; M2101K6G)"
          },
          "id" : {
            "type" : "string",
            "description" : "The login activity's unique ID.",
            "example" : "5432653"
          },
          "loginAt" : {
            "type" : "string",
            "description" : "The time the login took place.",
            "format" : "date-time"
          },
          "userId" : {
            "type" : "integer",
            "description" : "The user's unique ID.",
            "format" : "int32",
            "example" : 876
          },
          "email" : {
            "type" : "string",
            "description" : "Email address of the user associated with the login.",
            "example" : "person3@testdomain.com"
          },
          "loginSucceeded" : {
            "type" : "boolean",
            "description" : "Whether the login was successful or not."
          }
        },
        "description" : "Details about the a particular login activity for a HubSpot account.",
        "example" : {
          "countryCode" : "ie",
          "email" : "person3@testdomain.com",
          "id" : "5432653",
          "ipAddress" : "45.56.67.89",
          "loginAt" : "2022-04-01T19:36:24.303Z",
          "loginSucceeded" : true,
          "regionCode" : "d",
          "userAgent" : "Mozilla/5.0 (Linux; Android 11; M2101K6G)",
          "userId" : 876
        }
      },
      "ActingUser" : {
        "required" : [ "userId" ],
        "type" : "object",
        "properties" : {
          "userEmail" : {
            "type" : "string"
          },
          "userId" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "HydratedCriticalAction" : {
        "required" : [ "createdAt", "id", "type", "userId" ],
        "type" : "object",
        "properties" : {
          "createdAt" : {
            "type" : "string",
            "description" : "The time the activity took place.",
            "format" : "date-time"
          },
          "actingUser" : {
            "type" : "string",
            "description" : "Email address of the user associated with the activity.",
            "example" : "person3@testdomain.com"
          },
          "regionCode" : {
            "type" : "string",
            "description" : "The approximate region code",
            "example" : "d"
          },
          "infoUrl" : {
            "type" : "string",
            "description" : "A link to the URL where the action was taken in the account.",
            "example" : "app.hubspot.com/settings/123/users"
          },
          "countryCode" : {
            "type" : "string",
            "description" : "The approximate country code",
            "example" : "ie"
          },
          "ipAddress" : {
            "type" : "string",
            "description" : "IP address where the activity originated.",
            "example" : "45.56.67.89"
          },
          "location" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string",
            "description" : "The activity's unique ID.",
            "example" : "5432653"
          },
          "type" : {
            "type" : "string",
            "description" : "The type of activity.",
            "example" : "ADD_USER"
          },
          "userId" : {
            "type" : "integer",
            "description" : "The user's unique ID.",
            "format" : "int32",
            "example" : 876
          },
          "objectId" : {
            "type" : "string",
            "description" : "The ID of the affected object.",
            "example" : "7654"
          }
        },
        "description" : "Details about the a particular security activity for a HubSpot account.",
        "example" : {
          "actingUser" : "person3@testdomain.com",
          "countryCode" : "ie",
          "createdAt" : "2022-04-01T19:36:24.303Z",
          "id" : "5432653",
          "infoUrl" : "app.hubspot.com/settings/123/users",
          "ipAddress" : "45.56.67.89",
          "objectId" : "7654",
          "regionCode" : "d",
          "type" : "ADD_USER",
          "userId" : 876
        }
      },
      "Paging" : {
        "type" : "object",
        "properties" : {
          "next" : {
            "$ref" : "#/components/schemas/NextPage"
          },
          "prev" : {
            "$ref" : "#/components/schemas/PreviousPage"
          }
        }
      },
      "PortalInformationResponse" : {
        "required" : [ "accountType", "additionalCurrencies", "companyCurrency", "dataHostingLocation", "portalId", "timeZone", "uiDomain", "utcOffset", "utcOffsetMilliseconds" ],
        "type" : "object",
        "properties" : {
          "additionalCurrencies" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "utcOffset" : {
            "type" : "string"
          },
          "companyCurrency" : {
            "type" : "string"
          },
          "portalId" : {
            "type" : "integer",
            "format" : "int32"
          },
          "accountType" : {
            "type" : "string",
            "enum" : [ "STANDARD", "DEVELOPER_TEST", "SANDBOX", "APP_DEVELOPER" ]
          },
          "uiDomain" : {
            "type" : "string"
          },
          "timeZone" : {
            "type" : "string"
          },
          "dataHostingLocation" : {
            "type" : "string"
          },
          "utcOffsetMilliseconds" : {
            "type" : "integer",
            "format" : "int64"
          }
        }
      },
      "PublicApiUserActionEvent" : {
        "required" : [ "actingUser", "action", "category", "id", "occurredAt" ],
        "type" : "object",
        "properties" : {
          "actingUser" : {
            "$ref" : "#/components/schemas/ActingUser"
          },
          "subCategory" : {
            "type" : "string"
          },
          "occurredAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "targetObjectId" : {
            "type" : "string"
          },
          "action" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string"
          },
          "category" : {
            "type" : "string"
          }
        }
      },
      "Error" : {
        "required" : [ "category", "correlationId", "message" ],
        "type" : "object",
        "properties" : {
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : "{\"missingScopes\":[\"scope1\",\"scope2\"],\"invalidPropertyName\":[\"propertyValue\"]}"
          },
          "correlationId" : {
            "type" : "string",
            "description" : "A unique identifier for the request. Include this value with any error reports or support tickets",
            "format" : "uuid",
            "example" : "aeb5f871-7f07-4993-9211-075dc63e7cbf"
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            },
            "description" : "A map of link names to associated URIs containing documentation about the error or recommended remediation steps",
            "example" : "{\"knowledge-base\":\"https://www.hubspot.com/products/service/knowledge-base\"}"
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate",
            "example" : "Invalid input (details will vary based on the error)"
          },
          "category" : {
            "type" : "string",
            "description" : "The error category",
            "example" : "VALIDATION_ERROR"
          },
          "errors" : {
            "type" : "array",
            "description" : "further information about the error",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          }
        },
        "example" : {
          "message" : "Invalid input (details will vary based on the error)",
          "correlationId" : "aeb5f871-7f07-4993-9211-075dc63e7cbf",
          "category" : "VALIDATION_ERROR",
          "links" : {
            "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
          }
        }
      },
      "ErrorDetail" : {
        "required" : [ "message" ],
        "type" : "object",
        "properties" : {
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error"
          },
          "code" : {
            "type" : "string",
            "description" : "The status code associated with the error detail"
          },
          "in" : {
            "type" : "string",
            "description" : "The name of the field or parameter in which the error was found."
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "items" : {
                "type" : "string"
              }
            },
            "description" : "Context about the error condition",
            "example" : "{\"missingScopes\":[\"scope1\",\"scope2\"]}"
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate"
          }
        }
      },
      "ApiUsage" : {
        "required" : [ "collectedAt", "currentUsage", "fetchStatus", "name", "usageLimit" ],
        "type" : "object",
        "properties" : {
          "collectedAt" : {
            "type" : "string",
            "description" : "Indicates when the cache was last updated.",
            "format" : "date-time"
          },
          "usageLimit" : {
            "type" : "integer",
            "description" : "Limits by which a single integration can consume the HubSpot public APIs.",
            "format" : "int32"
          },
          "fetchStatus" : {
            "type" : "string",
            "description" : "Status of fetching the information, including if the data came from the cache.",
            "enum" : [ "SUCCESS", "TIMEOUT", "FAILURE", "CACHED", "NOTFOUND" ]
          },
          "name" : {
            "type" : "string",
            "description" : "Name of the limit type."
          },
          "currentUsage" : {
            "type" : "integer",
            "description" : "How many API calls an account has made for the current day.",
            "format" : "int32"
          },
          "resetsAt" : {
            "type" : "string",
            "description" : "Time that the limit will reset.",
            "format" : "date-time"
          }
        },
        "description" : "API usage and limits information for a HubSpot account."
      },
      "CollectionResponsePublicApiUserActionEvent" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PublicApiUserActionEvent"
            }
          },
          "paging" : {
            "$ref" : "#/components/schemas/Paging"
          }
        }
      },
      "PreviousPage" : {
        "required" : [ "before" ],
        "type" : "object",
        "properties" : {
          "before" : {
            "type" : "string",
            "description" : "A paging cursor token for retrieving previous pages."
          },
          "link" : {
            "type" : "string",
            "description" : "A URL that can be used to retrieve the previous pages' results."
          }
        },
        "description" : "specifies the paging information needed to retrieve the previous set of results in a paginated API response"
      },
      "CollectionResponseHydratedCriticalAction" : {
        "required" : [ "results" ],
        "type" : "object",
        "properties" : {
          "results" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/HydratedCriticalAction"
            }
          },
          "paging" : {
            "$ref" : "#/components/schemas/Paging"
          }
        }
      },
      "NextPage" : {
        "required" : [ "after" ],
        "type" : "object",
        "properties" : {
          "link" : {
            "type" : "string",
            "description" : "A URL that can be used to retrieve the next page results."
          },
          "after" : {
            "type" : "string",
            "description" : "A paging cursor token for retrieving subsequent pages."
          }
        },
        "description" : "Specifies the paging information needed to retrieve the next set of results in a paginated API response"
      }
    },
    "responses" : {
      "Error" : {
        "description" : "An error occurred.",
        "content" : {
          "*/*" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "account-info.security.read" : "Allows reading of account security information",
              "ACCEPTANCE_TEST.create.40420451.367186" : "Read from and write to my Social",
              "ACCEPTANCE_TEST.scopes.40420451.367375" : "Read from and write to my Social",
              "ACCEPTANCE_TEST.scopes.delete.40420451.368267" : "Read from and write to my Social",
              "ACCEPTANCE_TEST.both.40420451.367530" : "short foobar",
              "oauth" : "User and Account Information"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE"
  }
}