{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Url Redirects",
    "description" : "URL redirect operations",
    "version" : "v3",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "PROFESSIONAL",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "STARTER",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    },
    "x-hubspot-api-use-case" : "Redirect one page to another, or redirect an entire blog with one URL using flexible pattern variables.",
    "x-hubspot-related-documentation" : [ {
      "name" : "URL Redirects Guide",
      "url" : "https://developers.hubspot.com/docs/guides/api/cms/url-redirects"
    } ],
    "x-hubspot-introduction" : "Use the URL redirects API to redirect traffic from a HubSpot-hosted page or blog post to any URL. You can redirect pages to specific URLs or use flexible pattern redirects to redirect multiple pages using variables. Learn more about managing redirects in HubSpot."
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Redirects"
  } ],
  "paths" : {
    "/cms/v3/url-redirects/" : {
      "get" : {
        "tags" : [ "Redirects" ],
        "summary" : "Get current redirects",
        "description" : "Returns all existing URL redirects. Results can be limited and filtered by creation or updated date.",
        "operationId" : "get-/cms/v3/url-redirects/_getPage",
        "parameters" : [ {
          "name" : "after",
          "in" : "query",
          "description" : "The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : null
          }
        }, {
          "name" : "archived",
          "in" : "query",
          "description" : "Whether to return only results that have been archived.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "boolean",
            "example" : null
          }
        }, {
          "name" : "createdAfter",
          "in" : "query",
          "description" : "Only return redirects created after this date.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : null
          }
        }, {
          "name" : "createdAt",
          "in" : "query",
          "description" : "Only return redirects created on exactly this date.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : null
          }
        }, {
          "name" : "createdBefore",
          "in" : "query",
          "description" : "Only return redirects created before this date.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : null
          }
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "Maximum number of result per page",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer",
            "format" : "int32",
            "example" : null
          }
        }, {
          "name" : "sort",
          "in" : "query",
          "description" : "",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "array",
            "example" : null,
            "items" : {
              "type" : "string",
              "example" : null
            }
          }
        }, {
          "name" : "updatedAfter",
          "in" : "query",
          "description" : "Only return redirects last updated after this date.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : null
          }
        }, {
          "name" : "updatedAt",
          "in" : "query",
          "description" : "Only return redirects last updated on exactly this date.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : null
          }
        }, {
          "name" : "updatedBefore",
          "in" : "query",
          "description" : "Only return redirects last updated before this date.",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "format" : "date-time",
            "example" : null
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/CollectionResponseWithTotalUrlMappingForwardPaging"
                },
                "example" : {
                  "paging" : {
                    "next" : {
                      "after" : "Mg%3D%3D",
                      "link" : "https://api.hubspot.com/cms/v3/url-redirects?after=Mg%3D%3D"
                    }
                  },
                  "results" : [ {
                    "createdAt" : "2017-07-24T17:24:09.141Z",
                    "destination" : "http://www.example.online/{page_slug}",
                    "id" : "3212223134",
                    "isMatchFullUrl" : true,
                    "isMatchQueryString" : false,
                    "isOnlyAfterNotFound" : true,
                    "isPattern" : false,
                    "isProtocolAgnostic" : true,
                    "isTrailingSlashOptional" : true,
                    "precedence" : 3,
                    "redirectStyle" : 301,
                    "routePrefix" : "http://test.hs-sites.com/(?P<page_slug>.*)",
                    "updatedAt" : "2017-07-24T17:24:09.141Z"
                  }, {
                    "createdAt" : "2017-07-25T15:42:06.410Z",
                    "destination" : "/newtest/{page_slug}",
                    "id" : "3212242073",
                    "isMatchFullUrl" : true,
                    "isMatchQueryString" : false,
                    "isOnlyAfterNotFound" : true,
                    "isPattern" : false,
                    "isProtocolAgnostic" : true,
                    "isTrailingSlashOptional" : true,
                    "precedence" : 999999993,
                    "redirectStyle" : 301,
                    "routePrefix" : "/mytest/(?P<page_slug>.*)",
                    "updatedAt" : "2017-07-25T15:42:06.410Z"
                  } ],
                  "total" : 2
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      },
      "post" : {
        "tags" : [ "Redirects" ],
        "summary" : "Create a redirect",
        "description" : "Creates and configures a new URL redirect.",
        "operationId" : "post-/cms/v3/url-redirects/_create",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UrlMappingCreateRequestBody"
              },
              "example" : null
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UrlMapping"
                },
                "example" : null
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    },
    "/cms/v3/url-redirects/{urlRedirectId}" : {
      "get" : {
        "tags" : [ "Redirects" ],
        "summary" : "Get details for a redirect",
        "description" : "Returns the details for a single existing URL redirect by ID.",
        "operationId" : "get-/cms/v3/url-redirects/{urlRedirectId}_getById",
        "parameters" : [ {
          "name" : "urlRedirectId",
          "in" : "path",
          "description" : "The ID of the target redirect.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : null
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UrlMapping"
                },
                "example" : {
                  "createdAt" : "2017-07-24T17:24:09.141Z",
                  "destination" : "http://www.example.online/{page_slug}",
                  "id" : "3212223134",
                  "isMatchFullUrl" : true,
                  "isMatchQueryString" : false,
                  "isOnlyAfterNotFound" : true,
                  "isPattern" : false,
                  "isProtocolAgnostic" : true,
                  "isTrailingSlashOptional" : true,
                  "routePrefix" : "http://test.hs-sites.com/(?P<page_slug>.*)",
                  "updatedAt" : "2017-07-24T17:24:09.141Z"
                }
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Redirects" ],
        "summary" : "Delete a redirect",
        "description" : "Delete one existing redirect, so it is no longer mapped.",
        "operationId" : "delete-/cms/v3/url-redirects/{urlRedirectId}_archive",
        "parameters" : [ {
          "name" : "urlRedirectId",
          "in" : "path",
          "description" : "The ID of the target redirect.",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : null
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "Delete succeeded",
            "content" : { }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Redirects" ],
        "summary" : "Update a redirect",
        "description" : "Updates the settings for an existing URL redirect.",
        "operationId" : "patch-/cms/v3/url-redirects/{urlRedirectId}_update",
        "parameters" : [ {
          "name" : "urlRedirectId",
          "in" : "path",
          "description" : "",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : null
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UrlMapping"
              },
              "example" : null
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UrlMapping"
                },
                "example" : null
              }
            }
          },
          "default" : {
            "description" : "",
            "$ref" : "#/components/responses/Error"
          }
        },
        "security" : [ {
          "oauth2" : [ "content" ]
        }, {
          "private_apps" : [ "content" ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "ErrorDetail" : {
        "required" : [ "message" ],
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "description" : "The status code associated with the error detail",
            "example" : null
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "example" : null,
              "items" : {
                "type" : "string",
                "example" : null
              }
            },
            "description" : "Context about the error condition",
            "example" : "{missingScopes=[scope1, scope2]}"
          },
          "in" : {
            "type" : "string",
            "description" : "The name of the field or parameter in which the error was found.",
            "example" : null
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate",
            "example" : null
          },
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error",
            "example" : null
          }
        },
        "example" : null
      },
      "UrlMapping" : {
        "required" : [ "destination", "id", "isMatchFullUrl", "isMatchQueryString", "isOnlyAfterNotFound", "isPattern", "isProtocolAgnostic", "isTrailingSlashOptional", "precedence", "redirectStyle", "routePrefix" ],
        "type" : "object",
        "properties" : {
          "created" : {
            "type" : "string",
            "description" : "The date and time when the URL mapping was initially created.",
            "format" : "date-time",
            "example" : null
          },
          "destination" : {
            "type" : "string",
            "description" : "The destination URL, where the target URL should be redirected if it matches the `routePrefix`.",
            "example" : null
          },
          "id" : {
            "type" : "string",
            "description" : "The unique ID of this URL redirect.",
            "example" : null
          },
          "isMatchFullUrl" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match on the entire URL, including the domain.",
            "example" : null
          },
          "isMatchQueryString" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match on the entire URL path, including the query string.",
            "example" : null
          },
          "isOnlyAfterNotFound" : {
            "type" : "boolean",
            "description" : "Whether the URL redirect mapping should apply only if a live page on the URL isn't found. If False, the URL redirect mapping will take precedence over any existing page.",
            "example" : null
          },
          "isPattern" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match based on pattern.",
            "example" : null
          },
          "isProtocolAgnostic" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match both HTTP and HTTPS protocols.",
            "example" : null
          },
          "isTrailingSlashOptional" : {
            "type" : "boolean",
            "description" : "Whether a trailing slash will be ignored.",
            "example" : null
          },
          "precedence" : {
            "type" : "integer",
            "description" : "Used to prioritize URL redirection. If a given URL matches more than one redirect, the one with the **lower** precedence will be used.",
            "format" : "int32",
            "example" : null
          },
          "redirectStyle" : {
            "type" : "integer",
            "description" : "The type of redirect to create. Options include: 301 (permanent), 302 (temporary), or 305 (proxy). Find more details [here](https://knowledge.hubspot.com/cos-general/how-to-redirect-a-hubspot-page).",
            "format" : "int32",
            "example" : null
          },
          "routePrefix" : {
            "type" : "string",
            "description" : "The target incoming URL, path, or pattern to match for redirection.",
            "example" : null
          },
          "updated" : {
            "type" : "string",
            "description" : "The date and time when the URL mapping was last modified.",
            "format" : "date-time",
            "example" : null
          }
        },
        "example" : null
      },
      "ForwardPaging" : {
        "type" : "object",
        "properties" : {
          "next" : {
            "$ref" : "#/components/schemas/NextPage"
          }
        },
        "example" : null
      },
      "UrlMappingCreateRequestBody" : {
        "required" : [ "destination", "redirectStyle", "routePrefix" ],
        "type" : "object",
        "properties" : {
          "destination" : {
            "type" : "string",
            "description" : "The destination URL, where the target URL should be redirected if it matches the `routePrefix`.",
            "example" : null
          },
          "isMatchFullUrl" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match on the entire URL, including the domain.",
            "example" : null
          },
          "isMatchQueryString" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match on the entire URL path, including the query string.",
            "example" : null
          },
          "isOnlyAfterNotFound" : {
            "type" : "boolean",
            "description" : "Whether the URL redirect mapping should apply only if a live page on the URL isn't found. If False, the URL redirect mapping will take precedence over any existing page.",
            "example" : null
          },
          "isPattern" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match based on pattern.",
            "example" : null
          },
          "isProtocolAgnostic" : {
            "type" : "boolean",
            "description" : "Whether the `routePrefix` should match both HTTP and HTTPS protocols.",
            "example" : null
          },
          "isTrailingSlashOptional" : {
            "type" : "boolean",
            "description" : "Whether a trailing slash will be ignored.",
            "example" : null
          },
          "precedence" : {
            "type" : "integer",
            "description" : "Used to prioritize URL redirection. If a given URL matches more than one redirect, the one with the **lower** precedence will be used.",
            "format" : "int32",
            "example" : null
          },
          "redirectStyle" : {
            "type" : "integer",
            "description" : "The type of redirect to create. Options include: 301 (permanent), 302 (temporary), or 305 (proxy). Find more details [here](https://knowledge.hubspot.com/cos-general/how-to-redirect-a-hubspot-page).",
            "format" : "int32",
            "example" : null
          },
          "routePrefix" : {
            "type" : "string",
            "description" : "The target incoming URL, path, or pattern to match for redirection.",
            "example" : null
          }
        },
        "example" : null
      },
      "Error" : {
        "required" : [ "category", "correlationId", "message" ],
        "type" : "object",
        "properties" : {
          "category" : {
            "type" : "string",
            "description" : "The error category",
            "example" : null
          },
          "context" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "array",
              "example" : null,
              "items" : {
                "type" : "string",
                "example" : null
              }
            },
            "description" : "Context about the error condition",
            "example" : "{invalidPropertyName=[propertyValue], missingScopes=[scope1, scope2]}"
          },
          "correlationId" : {
            "type" : "string",
            "description" : "A unique identifier for the request. Include this value with any error reports or support tickets",
            "format" : "uuid",
            "example" : "aeb5f871-7f07-4993-9211-075dc63e7cbf"
          },
          "errors" : {
            "type" : "array",
            "description" : "further information about the error",
            "example" : null,
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            }
          },
          "links" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string",
              "example" : null
            },
            "description" : "A map of link names to associated URIs containing documentation about the error or recommended remediation steps",
            "example" : null
          },
          "message" : {
            "type" : "string",
            "description" : "A human readable message describing the error along with remediation steps where appropriate",
            "example" : "An error occurred"
          },
          "subCategory" : {
            "type" : "string",
            "description" : "A specific category that contains more specific detail about the error",
            "example" : null
          }
        },
        "example" : {
          "message" : "Invalid input (details will vary based on the error)",
          "correlationId" : "aeb5f871-7f07-4993-9211-075dc63e7cbf",
          "category" : "VALIDATION_ERROR",
          "links" : {
            "knowledge-base" : "https://www.hubspot.com/products/service/knowledge-base"
          }
        }
      },
      "NextPage" : {
        "required" : [ "after" ],
        "type" : "object",
        "properties" : {
          "after" : {
            "type" : "string",
            "description" : "The cursor value indicating where to begin fetching the next page of results in a paginated collection.",
            "example" : null
          },
          "link" : {
            "type" : "string",
            "description" : "An optional URL for directly accessing the next page of results.",
            "example" : null
          }
        },
        "description" : "Specifies the paging information needed to retrieve the next set of results in a paginated API response",
        "example" : null
      },
      "CollectionResponseWithTotalUrlMappingForwardPaging" : {
        "required" : [ "results", "total" ],
        "type" : "object",
        "properties" : {
          "paging" : {
            "$ref" : "#/components/schemas/ForwardPaging"
          },
          "results" : {
            "type" : "array",
            "example" : null,
            "items" : {
              "$ref" : "#/components/schemas/UrlMapping"
            }
          },
          "total" : {
            "type" : "integer",
            "description" : "The total number of URL mappings available.",
            "format" : "int32",
            "example" : null
          }
        },
        "example" : null
      }
    },
    "responses" : {
      "Error" : {
        "description" : "An error occurred.",
        "content" : {
          "*/*" : {
            "schema" : {
              "$ref" : "#/components/schemas/Error"
            },
            "example" : null
          }
        }
      }
    },
    "securitySchemes" : {
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "content" : "Content"
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "Node", "Python", "Ruby", "PHP" ],
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "PROFESSIONAL",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "STARTER",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}